# Site settings
title: Blog
url: "https://pennynd1me.github.io"
baseurl: ""
description: >
    블로그

# My information
email: 4prilkim@gmail.com
author: Jinhyun Kim
profile: 뚜
twitter_username: 
github_username: pennynd1me
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: pennynd1me
  shortname: pennynd1me
utterances:
  repo: pennynd1me/pennynd1me.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua:

google_adsense:
  client: 

blame: "https://github.com/pennynd1me/pennynd1me.github.io/blame/main/_wiki"
edit: "https://github.com/pennynd1me/pennynd1me.github.io/edit/main/_wiki"
issue: "https://github.com/pennynd1me/pennynd1me.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
